const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../model.js');const research=require('../data/research.json');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('425 MW, 40/50/10 at 12/20/40 gives $7.99B ARR',()=>{const r=M.calculate(research.profiles.NBIS.calculator);close(r.blended,18.8);close(r.arr,7990);close(r.ebit,1598);});
test('invalid inputs cannot become zero or normalized weights',()=>{for(const c of [{mix:[30,30,30]},{active_mw:NaN},{rates:[12,null,40]},{utilization:101},{margin:Infinity}])assert.throws(()=>M.calculate({...research.profiles.NBIS.calculator,...c}));});
test('revenue uses average capacity; exit ARR is not period revenue',()=>{const p={...research.profiles.NBIS,baseline_mw:0,tranches:[{id:'one',customer:'Test',mw:120,start:'2026-07',end:'2026-07',rate:12}],calculator:{active_mw:120,mix:[100,0,0],rates:[12,12,12],margin:20,utilization:100}};const r=M.forecast(p);close(r.rows[0].revenue_m,60);close(r.rows[0].exit_arr_m,1440);close(r.sums['2026'].revenue_m,660);});
test('customer stacks reconcile and preserve units',()=>{for(const p of Object.values(research.profiles)){const f=M.forecast(p);let previous=p.baseline_mw;for(const r of f.rows){close(Object.values(r.customers).reduce((a,b)=>a+b,0),r.total_mw);assert.ok(r.total_mw>=previous-1e-7);assert.equal(r.unit,p.unit);previous=r.total_mw;}close(previous,p.baseline_mw+p.tranches.reduce((a,t)=>a+t.mw,0));}});
test('delays preserve closed months and fixed deliveries; reduce future revenue',()=>{for(const p of Object.values(research.profiles)){const a=M.forecast(p),b=M.forecast(p,{delay:6});close(a.rows[0].total_mw,b.rows[0].total_mw);close(a.rows[1].total_mw,b.rows[1].total_mw);assert.ok(b.sums['2027'].revenue_m<=a.sums['2027'].revenue_m+1e-7);for(let i=0;i<a.rows.length;i++)for(const t of p.tranches.filter(t=>t.fixed))close(a.rows[i].parts.find(x=>x.id===t.id).mw,b.rows[i].parts.find(x=>x.id===t.id).mw);}});
test('missing denominator or incompatible scope/period suppresses ratios',()=>{assert.equal(M.ratio(5,0),null);assert.equal(M.ratio(null,5),null);assert.equal(M.derived({numerator:5,denominator:2,numeratorScope:'group',denominatorScope:'AI',numeratorPeriod:'Q2',denominatorPeriod:'Q2'}),null);assert.equal(M.derived({numerator:5,denominator:2,numeratorScope:'AI',denominatorScope:'AI',numeratorPeriod:'Q2',denominatorPeriod:'Q1'}),null);});
test('reverse months and dates before baseline are rejected',()=>{for(const patch of [{start:'2027-04',end:'2027-01'},{start:'2026-06',end:'2026-12'}])assert.throws(()=>M.forecast(research.profiles.NBIS,{tranches:[{...research.profiles.NBIS.tranches[0],...patch}]}));});
