/* Ensemble AI·Cloud — compact evidence, capacity and earnings workspace. */
(async function(){
'use strict';
const E=window.PhxCloud,M=window.CloudModel,root=document.getElementById('app');
const read=async name=>{const r=await fetch('data/'+name+'.json',{cache:'no-cache'});if(!r.ok)throw Error(name+': HTTP '+r.status);return r.json();};
const [ledger,research,archive,operations]=await Promise.all([read('ledger'),read('research'),read('phalanx'),read('operations').catch(()=>null)]);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
const pct=(a,b)=>typeof a==='number'&&typeof b==='number'&&b!==0?(a-b)/Math.abs(b)*100:null;
const signed=v=>v==null?'—':(v>0?'+':'')+n(v)+'%';
const safe=url=>{if(typeof url!=='string'||!url.trim())return '#';try{const u=new URL(url,location.href);return ['https:','http:'].includes(u.protocol)?esc(u.href):'#';}catch{return '#';}};
const link=(url,label)=>'<a href="'+safe(url)+'" target="_blank" rel="noopener">'+esc(label)+' ↗</a>';
const source=key=>{const s=research.sources[key];return s?link(s.url,s.label+' · '+s.published_at):'';};
const badge=(text,verified=false)=>'<span class="badge '+(verified?'verified':'')+'">'+esc(text)+'</span>';
const panel=(title,body,meta='')=>'<section class="panel"><h3>'+esc(title)+'</h3>'+body+(meta?'<p class="note">'+meta+'</p>':'')+'</section>';
const empty=text=>'<div class="empty">'+esc(text)+'</div>';
const table=(heads,rows)=>'<div class="table-wrap"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map((s,i)=>'<td'+(i===1?' class="num"':'')+'>'+s+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const groupNames={neocloud:'GPU 클라우드',colo:'임대·호스팅',hyperscaler:'하이퍼스케일러',china:'중화권'};
const colors={'Microsoft':'#55a8ff','Meta':'#b394ff','NVIDIA':'#76d394','CoreWeave':'#45c4d7','AWS':'#f5b658','Fluidstack':'#df89bd','미공개 IG 고객':'#bcad78','고객별 MW 미공개':'#607487','기존 고객·배분 미공개':'#607487'};
const palette=['#2bc0d4','#a991f7','#f7c56d','#4ed6a0','#f17d88'];
const color=customer=>colors[customer]||'#607487';
let svgID=0;
function svg(content,title,width=800,height=245){return '<svg class="chart" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(title)+'"><title>'+esc(title)+'</title>'+content+'</svg>';}
function bars(points,title,{unit='',colorValue=null,height=205}={}){
 const data=points.filter(p=>typeof p.value==='number'&&Number.isFinite(p.value));if(!data.length)return empty('이 범위에 표시할 수치가 없습니다.');
 const w=760,h=height,l=60,r=16,t=20,b=36,hi=Math.max(0,...data.map(p=>p.value))*1.15||1,lo=Math.min(0,...data.map(p=>p.value))*1.15,y=v=>t+(hi-v)/(hi-lo)*(h-t-b),step=(w-l-r)/data.length;
 let out='';for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;out+='<line class="grid" x1="'+l+'" x2="'+(w-r)+'" y1="'+y(v)+'" y2="'+y(v)+'"/><text x="'+(l-7)+'" y="'+(y(v)+4)+'" text-anchor="end">'+n(v,0)+'</text>';}
 data.forEach((p,i)=>{const x=l+i*step+step*.17,yy=y(Math.max(0,p.value)),bh=Math.abs(y(p.value)-y(0));out+='<rect x="'+x+'" y="'+yy+'" width="'+step*.66+'" height="'+Math.max(1,bh)+'" fill="'+(colorValue?colorValue(p,i):p.verified===false?'#5b7486':palette[i%palette.length])+'"><title>'+esc(p.label)+': '+n(p.value)+' '+esc(unit)+(p.verified===false?' · 기존 자료 미대조':'')+'</title></rect>';if(data.length<13||i%2===0)out+='<text x="'+(x+step*.33)+'" y="'+(h-15)+'" text-anchor="middle">'+esc(p.label)+'</text>';});
 return '<div class="chart-scroll">'+svg(out,title,w,h)+'</div>';
}
function lines(points,title,unit=''){
 if(!points.length)return empty('시계열이 아직 없습니다.');
 const w=760,h=220,l=64,t=20,b=38,r=22,hi=Math.max(...points.map(p=>p.value))*1.12||1,lo=Math.min(0,...points.map(p=>p.value))*1.12,y=v=>t+(hi-v)/(hi-lo)*(h-t-b),x=i=>l+(w-l-r)*i/Math.max(1,points.length-1);
 let out='';for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;out+='<line class="grid" x1="'+l+'" x2="'+(w-r)+'" y1="'+y(v)+'" y2="'+y(v)+'"/><text x="'+(l-7)+'" y="'+(y(v)+4)+'" text-anchor="end">'+n(v,0)+'</text>';}
 if(points.length>1)out+='<polyline points="'+points.map((p,i)=>x(i)+','+y(p.value)).join(' ')+'" fill="none" stroke="#6a859b" stroke-width="2" stroke-dasharray="4 4"/>';
 points.forEach((p,i)=>{out+='<circle cx="'+x(i)+'" cy="'+y(p.value)+'" r="'+(p.verified?4.5:3)+'" fill="'+(p.verified?'#4ed6a0':'#7b8b9c')+'"><title>'+esc(p.label)+' · '+n(p.value)+' '+esc(unit)+' · '+(p.verified?'공식 대조':'기존 자료 미대조')+'</title></circle>';if(points.length<9||i%Math.ceil(points.length/7)===0||i===points.length-1)out+='<text x="'+x(i)+'" y="'+(h-14)+'" text-anchor="middle">'+esc(p.label)+'</text>';});
 return '<div class="chart-scroll">'+svg(out,title,w,h)+'</div>';
}
function capacityChart(f,p){
 const rows=f.rows,w=1050,h=290,l=64,r=15,t=24,b=44,max=Math.max(...rows.map(x=>x.total_mw),1)*1.15,y=v=>h-b-v/max*(h-t-b),step=(w-l-r)/rows.length,pattern='hatch'+(++svgID);
 let out='<defs><pattern id="'+pattern+'" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><line x1="0" x2="0" y1="0" y2="7" stroke="#e9f1f5" stroke-opacity=".34" stroke-width="2"/></pattern></defs>';
 for(let i=0;i<=4;i++){const v=max*i/4;out+='<line class="grid" x1="'+l+'" x2="'+(w-r)+'" y1="'+y(v)+'" y2="'+y(v)+'"/><text x="'+(l-8)+'" y="'+(y(v)+4)+'" text-anchor="end">'+n(v,0)+'</text>';}
 rows.forEach((row,i)=>{let stack=0;const x=l+i*step+step*.14,bw=step*.72;row.parts.filter(t=>t.mw>0).forEach(part=>{const sy=y(stack+part.mw),bh=y(stack)-sy,tip=row.month+' · '+part.customer+' '+n(part.mw)+' '+p.unit+' · '+(part.mw_basis==='reported'?'계약/기준 물량 확인':'물량 추정')+' · '+(part.timing_basis==='reported'?'기준/인도월 확인':'월별 분할 추정');out+='<g><title>'+esc(tip)+'</title><rect x="'+x+'" y="'+sy+'" width="'+bw+'" height="'+bh+'" fill="'+color(part.customer)+'"/>'+(part.mw_basis!=='reported'?'<rect x="'+x+'" y="'+sy+'" width="'+bw+'" height="'+bh+'" fill="url(#'+pattern+')"/>':'')+'</g>';stack+=part.mw;});out+='<text x="'+(x+bw/2)+'" y="'+(y(stack)-6)+'" text-anchor="middle">'+n(stack,0)+'</text><text x="'+(x+bw/2)+'" y="'+(h-b+18)+'" text-anchor="middle">'+row.month.slice(5)+'</text>';if(row.month.endsWith('-01')||i===0)out+='<text x="'+(x+bw/2)+'" y="'+(h-5)+'" text-anchor="middle">'+row.month.slice(0,4)+'</text>';});
 const cut=rows.findIndex(r=>r.month==='2026-09');if(cut>=0)out+='<line x1="'+(l+cut*step)+'" x2="'+(l+cut*step)+'" y1="15" y2="'+(h-b)+'" stroke="#f7c56d" stroke-dasharray="3 4"/><text x="'+(l+cut*step+6)+'" y="14">기준월 2026-09</text>';
 const customers=[...new Set(rows.flatMap(r=>Object.keys(r.customers)))];
 return '<div class="chart-wrap">'+svg(out,'고객별 월말 용량 램프업, '+p.unit,w,h)+'</div><div class="legend">'+customers.map(c=>'<span><i style="background:'+color(c)+'"></i>'+esc(c)+'</span>').join('')+'<span>사선: MW 추정 · 월별 경로는 인도월 공시 외 추정</span></div>';
}
function kpis(items){return '<div class="kpis">'+items.map(([label,value,note])=>'<div class="kpi"><label>'+esc(label)+'</label><strong>'+esc(value)+'</strong><small>'+esc(note)+'</small></div>').join('')+'</div>';}
const params=new URLSearchParams(location.search),views={overview:'시그널',capacity:'월별 용량',earnings:'실적 변화',calculator:'계산기',history:'원본 데이터',evidence:'근거 원장',compare:'업체 비교',links:'상호연동'};
let id=Object.hasOwn(ledger.providers,params.get('company'))?params.get('company'):'NBIS',view=Object.hasOwn(views,params.get('view'))?params.get('view'):'overview',selectedMetric='',evidenceFilter='reviewed',evidenceSearch='',historyType='cloud';
const stores={};
function settings(){
 if(!research.profiles[id])return null;if(stores[id])return stores[id];
 let s={calculator:structuredClone(research.profiles[id].calculator),tranches:structuredClone(research.profiles[id].tranches),delay:0,price:0};
 try{const saved=JSON.parse(localStorage.getItem('ensemble-cloud-v2-'+id));if(saved){M.forecast(research.profiles[id],saved);s=saved;}}catch{}
 return stores[id]=s;
}
function persist(){try{localStorage.setItem('ensemble-cloud-v2-'+id,JSON.stringify(stores[id]));}catch{}}
const today=new Date().toISOString().slice(0,10),asof=today<research.updated?research.updated:today;
const allCurrent=E.current(ledger.signals,asof);
const rowsFor=p=>allCurrent.filter(s=>s.provider===p).sort((a,b)=>(Number(b.verified)-Number(a.verified))||String(b.effective_at||b.period).localeCompare(String(a.effective_at||a.period)));
function forecast(){return M.forecast(research.profiles[id],settings());}
function getHistory(){
 const rows=rowsFor(id),groups={};for(const s of rows){if(typeof s.value!=='number')continue;const key=s.metric+'|'+s.scope+'|'+s.unit;if(!groups[key])groups[key]={label:s.title,unit:s.unit,scope:s.scope,points:[]};groups[key].points.push({label:s.period,value:s.value,verified:s.verified,source:s.source_url});}
 return groups;
}
function earnings(){
 const p=research.profiles[id];if(!p)return panel('공식 실적 관측',evidenceTable(rowsFor(id).filter(s=>s.verified)), '분기 원자료 대조가 끝난 항목부터 표시합니다. 과거 자료는 원본 데이터에서 확인할 수 있습니다.');
 const rows=p.changes.map(c=>{let delta=c.kind==='milestone'?(c.after-c.before)+'개월':signed(pct(c.after,c.before));return [esc(c.label)+' '+badge(c.kind==='target'?'회사 목표':c.kind==='milestone'?'인도 확인':'공식 대조',c.kind!=='target'),n(c.before)+' → '+n(c.after)+' '+esc(c.unit),esc(delta),esc(c.periods.join(' → ')),esc(c.note)+'<br>'+source(c.source)];});
 let comparisons=p.changes.filter(c=>typeof c.before==='number'&&c.before>0&&c.kind==='actual');
 const chart=bars(comparisons.map(c=>({label:c.label,value:pct(c.after,c.before),verified:true})),'실적 변화율',{unit:'%',colorValue:p=>p.value<0?'#f17d88':'#2bc0d4'});
 const derived=(p.derived||[]).length?panel('현금·선수금·계약 파생 지표',table(['지표','값','산식·사업 범위','출처'],p.derived.map(d=>[esc(d.label),n(d.value)+' '+esc(d.unit),esc(d.formula),source(d.source)]))):'';
 return panel('실적 발표에서 무엇이 바뀌었나',chart+table(['지표','이전 → 현재','변화','비교 기간','근거'],rows),'서로 다른 비교 기간을 각 행에 표시했습니다. 매출 증가와 현금 부담은 별도 판정합니다.')+derived+contracts()+methodology();
}
function contracts(){const p=research.profiles[id];return p?panel('고객별 계약 · 배정 근거',table(['고객','공개 MW','총 계약액 / 기간','M USD/MW·년','확인 범위'],p.contracts.map(c=>[esc(c.customer),c.mw==null?'미공개':n(c.mw)+' '+esc(c.capacity_basis==='gross'?'gross MW':'IT MW'),(c.tcv_m==null?'미공개':'$'+n(c.tcv_m/1000,2)+'B')+' / '+(c.years==null?'미공개':c.years+'년'),n(c.rate,2),esc(c.note)+'<br>'+source(c.source)])),'계약액÷계약연수÷MW는 평균 연간 계약강도입니다. GPU 렌탈 가격과 임대료는 같은 상품이 아닙니다.') :'';}
function methodology(){return panel('Calculator / Methodology',research.methodology.formulas.map(f=>'<p class="formula">'+esc(f)+'</p>').join('')+'<details><summary>계산에서 제외한 항목과 데이터 원칙</summary><ul>'+research.methodology.rules.map(r=>'<li>'+esc(r)+'</li>').join('')+'<li>연말 ARR을 연간 매출로 쓰지 않습니다. 선수수익은 RPO가 아니며, 전체 TCV에 옵션·보증·잔여 용량 약정을 중복 합산하지 않습니다.</li><li>CAPEX/MW는 동일 기간의 증가 용량, 선수금 커버는 해당 계약 CAPEX가 있어야 계산합니다. 분모 미공개 시 —로 남깁니다.</li></ul></details><p class="note">참고: '+link('https://nbistracker.com/earnings','Earnings')+' · '+link('https://nbistracker.com/calculator','Calculator')+' · '+link('https://nbistracker.com/methodology','Methodology')+'</p>');}
function evidenceTable(rows){return rows.length?table(['관측 · 기간','값','판정','원문·발견·검증'],rows.map(s=>[esc(s.title)+'<div class="meta">'+esc(s.period)+' · '+esc(s.scope)+'</div>',n(s.value)+' '+esc(s.unit),badge(s.verified?(s.evidence==='confirmed'?'공식 대조':'회사 목표'):'기존 자료',s.verified&&s.evidence==='confirmed')+'<div class="meta">'+esc(E.excluded(s,asof)||s.rule)+'</div>',link(s.source_url,'원문')+'<div class="meta">공표 '+esc(s.published_at||'미확인')+' · 발견 '+esc(s.first_seen_at||s.observed_at)+' · 검증 '+esc(s.verified_at||'미실시')+' · v'+esc(s.revision)+'</div><details><summary>범위·수정 이력</summary>'+esc(s.note)+'<br>'+ledger.signals.filter(x=>x.key===s.key).map(x=>'v'+x.revision+' · '+esc(x.observed_at)+' · '+n(x.value)+' '+esc(x.unit)).join('<br>')+'</details>'])):empty('선택한 조건의 근거가 없습니다.');}
function filteredEvidence(){return rowsFor(id).filter(s=>(evidenceFilter==='all'||(evidenceFilter==='reviewed'?s.verified:!s.verified))&&[s.title,s.note,s.scope,s.period].join(' ').toLowerCase().includes(evidenceSearch.toLowerCase()));}
function evidence(){return panel('근거 원장', '<div class="toolbar"><select id="evidence-filter" aria-label="근거 분류"><option value="reviewed"'+(evidenceFilter==='reviewed'?' selected':'')+'>공식 대조·목표</option><option value="all"'+(evidenceFilter==='all'?' selected':'')+'>전체</option><option value="legacy"'+(evidenceFilter==='legacy'?' selected':'')+'>기존 자료 미대조</option></select><input id="evidence-search" value="'+esc(evidenceSearch)+'" placeholder="지표·기간·근거 검색" aria-label="근거 검색"><button data-action="evidence-csv">선택 근거 CSV</button><span id="evidence-count" class="meta">'+filteredEvidence().length+'개</span></div><div id="evidence-rows">'+evidenceTable(filteredEvidence())+'</div>','기존 자료의 자체 confidence와 공식 검증 여부를 구분합니다. 미검증·목표는 관측 점수에서 제외합니다.');}
function ramp(){
 const p=research.profiles[id];if(!p)return panel('월별 용량',empty('공개된 MW 기준점·계약별 인도 일정이 부족해 이 업체의 월별 용량 추정은 비워 두었습니다.')+'<p class="note">업체별 공시 범위와 원본 시계열은 실적 변화·원본 데이터에서 확인할 수 있습니다.</p>');
 const s=settings(),f=forecast();
 const edit=table(['고객 / 프로젝트','추가 MW','시작월','완료월','물량·일정 근거'],s.tranches.map((t,i)=>[esc(t.customer)+'<div class="meta">'+esc(t.title)+'</div>','<input class="mw-input" type="number" min="0" max="100000" step="0.1" data-tranche="'+i+'" data-field="mw" value="'+nRaw(t.mw)+'" aria-label="'+esc(t.title)+' MW"'+(t.fixed?' disabled':'')+'>','<input type="month" min="2026-07" max="2030-12" data-tranche="'+i+'" data-field="start" value="'+t.start+'" aria-label="'+esc(t.title)+' 시작월"'+(t.fixed?' disabled':'')+'>','<input type="month" min="2026-07" max="2030-12" data-tranche="'+i+'" data-field="end" value="'+t.end+'" aria-label="'+esc(t.title)+' 완료월"'+(t.fixed?' disabled':'')+'>',badge(t.mw_basis==='reported'?'계약 MW 확인':'MW 가정',t.mw_basis==='reported')+' '+badge(t.fixed?'실제 인도월':'월 분할 추정')+'<div class="meta">'+esc(t.note)+'</div>'+source(t.source)]));
 return capacityPanel(f,p)+panel('램프업 입력 · 고객별 월간 인도 시나리오','<div class="toolbar"><label>추가 지연 <select id="delay">'+[0,1,2,3,6,9,12].map(v=>'<option '+(s.delay===v?'selected ':'')+'value="'+v+'">'+v+'개월</option>').join('')+'</select></label><button data-action="reset">기본 가정 복원</button><button data-action="ramp-csv">월별 용량·매출 CSV</button><span id="form-error" class="negative" role="alert"></span></div>'+edit+'<p class="note">기준: '+esc(p.baseline_month)+' · '+n(p.baseline_mw)+' '+esc(p.unit)+' · '+esc(p.baseline_note||p.scope)+'</p><ul class="notes">'+p.notes.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>','값을 바꾸면 사용자 가정으로 저장됩니다. 추가 지연은 2026-08까지의 경로와 확인된 인도월을 보존하고 이후 잔여 물량에 적용합니다.')+panel('월 매출 시나리오',bars(f.rows.map(r=>({label:r.month.slice(2),value:r.revenue_m})),'월 매출 시나리오',{unit:'USD M',colorValue:()=> '#2bc0d4'})+monthlyTable(f),'월평균 수익화 용량 × 계약별 연간 단가 ÷12. 매출 인식·램프 형태·가동률을 단순화한 추정입니다.')+contracts();
}
const nRaw=v=>Math.round(v*1000000)/1000000;
function monthlyTable(f){return '<details><summary>월별 수치와 고객 배정 펼치기</summary>'+table(['월','월말 MW','월평균 MW','월 매출 USD M','연율 매출 USD M','고객별 MW'],f.rows.map(r=>[r.month,n(r.total_mw),n(r.average_mw),n(r.revenue_m),n(r.exit_arr_m),Object.entries(r.customers).filter(([,v])=>v>0).map(([c,v])=>esc(c)+' '+n(v)).join(' · ')]))+'</details>';}
function capacityPanel(f,p){return panel('월별 용량 램프업 · 고객 배정', '<div class="inline"><span class="meta">'+esc(p.scope)+' · '+esc(p.unit)+'</span><button data-view="capacity">가정 조정</button><button data-action="ramp-csv">CSV</button></div>'+capacityChart(f,p), '확인된 고객 물량은 고객 색상, 미공개 배정은 회색, MW 추정은 사선으로 표시합니다. 막대는 월말 용량입니다. '+source(p.source));}
function calculator(){
 const p=research.profiles[id];if(!p)return panel('용량 기반 매출 계산',empty('이 업체는 공개 용량과 계약 단가의 일관된 분모가 없어 기본 시나리오를 제공하지 않습니다.')+methodology());
 const c=settings().calculator,names=id==='NBIS'?['장기 전용','중기 계약','단기 탄력']:['기준 계약','대안 단가 1','대안 단가 2'];
 return panel('연율 매출 계산기 · 모든 입력은 시나리오','<div class="calc-inputs">'+[['active_mw','수익화 MW',0,100000],['utilization','가동률 %',0,100],['margin','EBIT 마진 %',-100,100]].map(([key,title,min,max])=>'<label>'+title+'<input type="number" data-calc="'+key+'" value="'+c[key]+'" min="'+min+'" max="'+max+'" step="0.1"></label>').join('')+'</div>'+table(['계약 유형','비중 %','연간 단가 M USD/MW','근거'],names.map((name,i)=>[name,'<input type="number" min="0" max="100" step="1" data-mix="'+i+'" value="'+c.mix[i]+'" aria-label="'+name+' 비중">','<input type="number" min="0" max="1000" step="0.1" data-rate="'+i+'" value="'+nRaw(c.rates[i])+'" aria-label="'+name+' 연간 단가">',id==='NBIS'?['12M 참고 계산기 가정','회사 신규 계약 20–25M 범위 중 20','회사 단기 40–50M 범위 중 40'][i]:'계약액/연수/MW 또는 명시된 단가 가정']))+'<div class="toolbar section-gap"><button data-action="reset">기본 가정 복원</button><span id="calc-error" class="negative" role="alert"></span></div><p class="note">비중 합계는 100%여야 합니다. 위 MW는 단독 ARR 계산에 사용하며 월별 용량 경로는 ‘월별 용량’에서 수정합니다. 단가·가동률·마진은 월별 모델에도 반영됩니다.</p>')+'<div id="calc-output">'+calcOutput()+'</div>'+methodology();
}
function calcOutput(){
 const p=research.profiles[id],s=settings(),c=M.calculate(s.calculator),f=forecast(),base=f.sums['2027'].revenue_m;
 const sensitivity=M.sensitivity(p,s);
 return kpis([['혼합 연간 단가','$'+n(c.blended,2)+'M','MW당 연간 · 유형별 가중평균'],['연율 매출 ARR','$'+n(c.arr/1000,2)+'B','가정 MW × 단가 × 가동률'],['연율 EBIT','$'+n(c.ebit/1000,2)+'B','ARR × 가정 EBIT 마진'],['2027 기간 매출','$'+n(base/1000,2)+'B','12개월 평균 용량 합계 · 추정']])+ '<div class="grid2">'+panel('계약 유형별 ARR 기여',bars(c.segments.map((v,i)=>({label:['유형 1','유형 2','유형 3'][i],value:v})),'유형별 ARR',{unit:'USD M'}))+panel('연도별 기간 매출 · 연말 연율 매출',table(['기간','기간 매출','연말 연율 매출','월 수'],Object.entries(f.sums).map(([y,v])=>[y==='2026'?'2026 H2':y,'$'+n(v.revenue_m/1000,2)+'B','$'+n(v.exit_arr_m/1000,2)+'B',String(v.months)])),'2026은 하반기 6개월만 포함합니다. 전사 연간 실적과 직접 비교하지 않습니다.')+'</div>'+panel('2027 매출 민감도 · 인도 지연 × 계약 단가',table(['추가 지연','단가 −20%','−10%','기준','+10%','+20%'],sensitivity.map(row=>[row.delay+'개월',...row.values.map(v=>'<span class="heat-value" style="background:rgba(43,192,212,'+(.06+.28*Math.min(1.5,v.revenue_m/Math.max(base,1))/1.5)+')">$'+n(v.revenue_m/1000,2)+'B</span>')])),'월별 가정 경로의 민감도이며 확률구간이 아닙니다. 개별 계약에 지정된 단가는 유형 비중보다 우선합니다.');
}
function history(){
 const groups=getHistory(),keys=Object.keys(groups);if(!groups[selectedMetric])selectedMetric=keys.find(k=>k.startsWith('cloud_revenue|'))||keys[0]||'';
 const g=groups[selectedMetric];
 const revenue=g?panel('업체별 원본 시계열','<div class="toolbar"><select id="metric" aria-label="시계열 지표">'+keys.map(k=>'<option value="'+esc(k)+'"'+(k===selectedMetric?' selected':'')+'>'+esc(groups[k].label+' · '+groups[k].unit+' · '+groups[k].scope)+'</option>').join('')+'</select></div>'+lines(g.points.slice().sort((a,b)=>a.label.localeCompare(b.label)),g.label,g.unit)+'<p class="note">'+esc(g.scope)+' · '+esc(g.unit)+' · 초록 점: 공식 대조 / 회색 점·점선: 기존 자료 미대조</p>'+table(['기간','값','검증','원문'],g.points.slice().sort((a,b)=>b.label.localeCompare(a.label)).map(p=>[esc(p.label),n(p.value)+' '+esc(g.unit),badge(p.verified?'공식 대조':'기존 자료',p.verified),link(p.source,'원문')]))):panel('원본 시계열',empty('공개 수치가 없는 업체입니다.'));
 const cap=archive.capex?.companies?.[id];let capPanel='';if(cap){capPanel=panel('CAPEX·FCF 공통 시계열','<div class="grid2">'+['capex','fcf'].map(key=>'<div><h3>'+key.toUpperCase()+' · '+esc(cap.ccy)+' M</h3>'+lines(Object.entries(cap[key]||{}).slice(-12).map(([label,value])=>({label,value,verified:false})),key,cap.ccy+' M')+'</div>').join('')+'</div>','팔랑크스 공통 CAPEX 원본을 옮긴 스냅샷 · 원장 점수에는 재사용하지 않습니다. '+esc(cap.capex_def||'')+' 기준일 '+esc(archive.capex._meta.asof));}
 const aspID={AMZN:'AWS',MSFT:'Azure',GOOGL:'GCP',ORCL:'OCI','9988.HK':'Alibaba Cloud','0700.HK':'Tencent Cloud','9888.HK':'Baidu AI Cloud'}[id],asp=archive.asp?.providers?.[aspID];let aspPanel='';if(asp){const implied=asp.consensus?.implied_asp||{},recalc=asp.recalc?.blended_asp||{};aspPanel=panel('기존 ASP 추정 · 비교용 보존',table(['기간','기존 암시 단가','계약 믹스 재계산','단위'],[...new Set([...Object.keys(implied),...Object.keys(recalc)])].map(y=>[esc(y),n(implied[y]),n(recalc[y]),'M USD/MW·년'])),'기존 외부 추정의 원자료를 이번에 재대조하지 않았습니다. 현재 가동 MW나 확정 컨센서스로 사용하지 않습니다. '+esc(asp.consensus?.gw_basis||''));}
 const tx=archive.tx?.[id];const calls=tx?.calls||[];const callsPanel=calls.length?panel('컨퍼런스콜 근거 연결',table(['기간','기존 분류 수','확인 경로'],calls.map(c=>[esc(c.quarter),String((c.quotes||[]).length),link(c.src,'기존 원문 경로')+'<div class="meta">'+esc(c.note||'')+'</div>'])),'기존 콜 분류와 출처를 보존했습니다. 재대조 전 내용은 신규 확정 신호로 세지 않습니다.'):'';
 return revenue+capPanel+aspPanel+callsPanel+panel('AI·클라우드 원본 데이터', '<div class="inline"><a href="data/phalanx.json" download>전체 데이터 JSON ↓</a><a href="data/ledger.json" download>관측 원장 JSON ↓</a></div>','매출·CAPEX·FCF·ASP·네오클라우드·콜 분류·역산 가정 데이터를 포함합니다. 업체별 통화와 세그먼트 범위를 보존합니다.');
}
function operationsPanel(){
 if(id!=='NBIS')return '';
 if(!operations)return panel('운영 선행 관측',empty('운영 데이터 로드 실패. 다음 갱신을 확인하세요.'));
 const a=operations.adapters,jobs=a.jobs?.rows||[],dc=jobs.filter(j=>j.data_center),regions=a.regions?.rows||[],locations={};dc.forEach(j=>{locations[j.location]=(locations[j.location]||0)+1;});
 const snapshots=operations.snapshots||[],events=(operations.events||[]).slice(-8).reverse(),fresh=Object.entries(a).map(([kind,v])=>{const age=v.updated_at?(Date.now()-Date.parse(v.updated_at))/86400000:Infinity;return badge(({jobs:'채용',regions:'리전',incidents:'장애'}[kind])+': '+(v.health==='ok'&&age<3?'갱신 정상':'갱신 확인 필요'),v.health==='ok'&&age<3)+' <span class="meta">'+esc(v.updated_at?.slice(0,16)||'미수집')+'</span>';}).join(' · ');
 return panel('운영 선행 관측 · 공식 공개 API', '<div class="inline">'+fresh+'</div>'+kpis([['채용 공고',String(jobs.length),'현재 열려 있는 공고 수'],['DC 관련 직무',String(dc.length),'직무 제목의 DC·커미셔닝 분류'],['상태 페이지 리전',String(regions.length),'서비스 컴포넌트와 구분'],['관측 후 변화',String(operations.events?.length||0),'최초 수집은 신규 채용으로 세지 않음']])+'<div class="grid2"><div><h3>DC 채용 · 지역 분포</h3>'+bars(Object.entries(locations).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label:label.length>16?label.slice(0,15)+'…':label,value})),'DC 채용 지역별 현재 공고',{unit:'개'})+'</div><div><h3>리전 상태</h3>'+table(['리전','현재 상태'],regions.map(r=>[esc(r.name),badge(r.status,r.status==='operational')]))+'</div></div>'+(snapshots.length>1?lines(snapshots.map(s=>({label:s.date.slice(5),value:s.dc_jobs,verified:true})),'수집 이후 DC 채용 공고 수','개'):'<p class="note">시계열 시작 '+esc(snapshots[0]?.date||'—')+'. 과거 채용 날짜를 만들어 채우지 않습니다. 공고 수정일은 최초 게시일이 아닙니다.</p>')+'<details><summary>최근 변화·직무·장애 근거</summary>'+table(['발견','변화','원문'],events.map(e=>[esc(e.at.slice(0,10)),esc(e.type+' · '+e.label),link(e.url,'원문')]))+table(['직무','지역','게시 경로'],dc.slice(0,15).map(j=>[esc(j.title),esc(j.location),link(j.url,'공고')]))+table(['발생일','최근 장애','상태'],(a.incidents?.rows||[]).slice(0,6).map(i=>[esc(i.created_at.slice(0,10)),link(i.url,i.title),esc(i.status)]))+'</details>','채용·서비스 상태는 가동 MW의 직접 증거가 아닙니다. 장애 API의 최근 50건으로 가동률이나 SLA를 계산하지 않습니다. '+link(a.jobs?.url,'채용 API')+' · '+link(a.regions?.url,'상태 API'));
}
function observationSummary(provider){
 const result=E.ensemble(ledger.signals,provider,asof);
 return '<div class="axis-strip">'+Object.entries(E.AXES).map(([axis,title])=>{const v=result.axes[axis];return '<div><span>'+title+'</span><b class="'+(v?(v.direction>0?'positive':v.direction<0?'negative':''):'muted')+'">'+(v?(v.direction>0?'개선':v.direction<0?'부담':'혼재'):'근거 미확보')+'</b><small>'+E.WEIGHTS[axis]+'%</small></div>';}).join('')+'</div><p class="note">관측 범위 '+result.coverage+'% · '+result.source_count+'개 원문 · '+(result.score==null?'종합 점수 보류':'방향 점수 '+result.score+'/100')+'. 동일 원문의 여러 항목은 독립 근거가 아닙니다. 상승 확률·수익률 예측이 아닙니다.</p>';
}
function overview(){
 const p=research.profiles[id],rows=rowsFor(id),verified=rows.filter(s=>s.verified&&s.evidence==='confirmed');
 let top='';if(p){const f=forecast(),rev=p.changes.find(c=>c.label.includes('매출')&&c.unit==='USD M'),end=f.sums['2026'],next=f.rows.filter(r=>r.month>='2026-09'&&r.month<='2026-11'),prior=f.rows.find(r=>r.month==='2026-08'),increment=next.at(-1).total_mw-prior.total_mw;
 top=kpis([[rev?.label||'공식 실적 근거',rev?'$'+n(rev.after)+'M':verified.length+'개',rev?rev.periods[1]+' · '+signed(pct(rev.after,rev.before)):'최근 공표일 기준'],['2026-12 월말 용량',n(end.end_mw)+' MW',p.unit+' · 시나리오'],['2026 H2 기간 매출','$'+n(end.revenue_m/1000,2)+'B','월평균 용량 6개월 합계 · 추정'],['2027 기간 매출','$'+n(f.sums['2027'].revenue_m/1000,2)+'B','고객·단가·일정 가정 반영']]);
 const highlights=id==='NBIS'?[['수요: ARR와 신규 계약 동반 증가','Q2 ARR $3.0B, 전분기 대비 '+signed(pct(3000,1920))+'. 신규 TCV 약 4배 QoQ.','nbis_q2'],['인도: 목표와 실물 용량 구분','연말 계약 전력 5GW는 가동 전력이 아닙니다. 425MW는 참고 계산기의 수익화 시나리오입니다.','nbis_q2'],['현금: 성장과 자금 부담 동시 확대','Q2 OCF $2.25B − 현금 CAPEX $5.66B = FCF −$3.41B. 선수수익 $5.98B는 RPO와 다릅니다.','nbis_fin']]:[[p.scope,'확인된 기준점과 계약별 월간 추정치를 분리합니다.',p.source],['향후 3개월 인도 추정','9–11월 +'+n(increment)+' '+p.unit+'. 개별 인도월을 바꾸면 매출 경로가 즉시 바뀝니다.',p.source],['계약의 경제성 범위','GPU 서비스·시설 임대·전사 채굴 포함 매출을 서로 다른 기준으로 표시합니다.',p.source]];
 top+='<div class="signals">'+highlights.map(([title,note,src])=>'<article class="signal"><b>'+esc(title)+'</b><p>'+esc(note)+'</p><span class="meta">'+source(src)+'</span></article>').join('')+'</div>'+capacityPanel(f,p)+'<div class="grid2">'+panel('매출 전환 경로',bars(f.rows.map(r=>({label:r.month.slice(2),value:r.revenue_m})),'월 매출 시나리오',{unit:'USD M',colorValue:()=> '#2bc0d4'}),'월평균 용량 기반 · USD M · 추정')+panel('다음 확인 지점',table(['점검','시나리오 / 확인할 값'],[['9–11월 추가 용량',n(increment)+' '+esc(p.unit)],['2026-12 연율 매출','$'+n(end.exit_arr_m/1000,2)+'B'],['3개월 지연 시 2027 매출','$'+n(M.forecast(p,{...settings(),delay:3}).sums['2027'].revenue_m/1000,2)+'B'],['필요한 후속 근거','실제 인도 공시·고객별 MW·분기 매출·현금 CAPEX']]),'추정치를 실제 인도와 다음 실적 발표로 대조합니다.')+'</div>';
 }else{top=kpis([['공식 대조 관측',verified.length+'개','기준일 '+asof],['보존한 기존 관측',rows.filter(s=>!s.verified).length+'개','원본 데이터에서 그래프 확인'],['공시 범위',ledger.providers[id].currency,'통화·세그먼트별 비교'],['월별 용량','근거 대기','임의의 MW를 채우지 않음']]);const h=getHistory(),g=Object.values(h).sort((a,b)=>b.points.length-a.points.length)[0];if(g)top+=panel(g.label,lines(g.points.slice().sort((a,b)=>a.label.localeCompare(b.label)),g.label,g.unit),esc(g.unit)+' · '+esc(g.scope)+' · 회색: 기존 자료 미대조');top+=panel('공시 범위',esc(ledger.providers[id].definition||'시설 임대·전사 매출·GPU 서비스의 귀속 범위를 원문에서 확인합니다.'));}
 return top+panel('실제 관측의 방향',observationSummary(id))+panel('핵심 근거',evidenceTable(verified.slice(0,8)))+operationsPanel();
}
function compare(){
 const providers=Object.values(ledger.providers);return panel('22개 업체 관측 지도',table(['업체','수요','가동','계약','단가','자금','관측 범위 / 원문','용량 모델'],providers.sort((a,b)=>a.group.localeCompare(b.group)).map(p=>{const e=E.ensemble(ledger.signals,p.id,asof);return ['<button class="text-button" data-company="'+esc(p.id)+'">'+esc(p.id)+'</button><div class="meta">'+esc(groupNames[p.group])+'</div>',...Object.keys(E.AXES).map(k=>{const a=e.axes[k];return '<span class="heat-value '+(a?(a.direction>0?'positive':a.direction<0?'negative':''):'muted')+'">'+(a?(a.direction>0?'▲ 개선':a.direction<0?'▼ 부담':'● 혼재'):'—')+'</span>';}),e.coverage+'% / '+e.source_count+'개',research.profiles[p.id]?esc(research.profiles[p.id].unit):'공개 MW 부족'];})),'가중치: 수요 30 · 인도 25 · 계약 20 · 단가 15 · 자금 10. 2축·40% 미만은 점수 보류. 180일 초과 관측 제외, 90일 반감기로 최근 근거에 더 큰 비중. 목표·추정·미검증 제외.')+panel('비교 가능한 것과 추가 검증이 필요한 것',table(['구분','비교 기준'],[['하이퍼스케일러','세그먼트 매출 성장·영업이익. Azure 성장률과 Google Cloud 전체 매출을 금액으로 직접 합산하지 않음.'],['GPU 클라우드','매출·ARR·수익화 용량·현금 부담. 고객별 물량과 단가가 없으면 미공개 유지.'],['시설 임대·호스팅','IT MW 또는 gross MW별 계약액/연수. GPU 렌탈 매출 단가와 구분.'],['중화권','CNY, 결산기·클라우드 세그먼트 변화 확인. 기존 오프라인 수치 재검증 필요.']]))+ '<p class="note">기준일 '+asof+' · '+link('data/ledger.json','관측 데이터')+'</p>';
}
function integration(){
 const projects=ledger.integration.projects[id]||[],checks=[['서버·랙','rack','계약·인도 분기 → ODM 매출·서버 공급','조건부','고객별 공급 배분과 0–2분기 시차 확인'],['HBM·메모리','memory','GPU 세대 → HBM 구성·공급사','조건부','DDR5 현물가를 HBM 계약단가로 쓰지 않음'],['광·네트워크','optics','클러스터 인도 → 스위치·광모듈 수요','조건부','네트워크 구성·업체별 BOM 필요'],['전력·냉각','power','IT/gross MW → 전력기기·냉각','조건부','PUE·계약 귀속·발주 시점 필요']];
 return panel('앙상블 공급망 연결',table(['이동','연결 기준','상태','다음 검증'],checks.map(([name,path,key,state,note])=>['<a href="../chains/'+path+'.html" target="_top">'+name+' ↗</a>',esc(key),badge(state),esc(note)])),'공통 기업 ID·월/분기·공표일을 연결 키로 사용합니다. 상관계수·예측 모델 편입은 아직 검증되지 않았습니다.')+panel('팔랑크스 원본 프로젝트 연결',projects.length?table(['프로젝트','기존 현재 MW','계획 MW','연결 근거'],projects.map(p=>[esc(p.name||p.id),n(p.current_mw),n(p.planned_mw||p.capacity_mw),esc(p.source||p.note||'기존 프로젝트 매핑; 운영사·고객 구분 필요')])):empty('이 업체에 매핑된 기존 데이터센터 프로젝트가 없습니다.'),'기존 프로젝트의 현재·계획 수치는 원자료 미대조입니다. 위 월별 모델에 자동 합산하지 않습니다.')+panel('중복 방지와 상호연동 상태',table(['데이터','키','검증 결과'],ledger.integration.checks.map(c=>[esc(c.title),esc(c.key),esc(c.detail)])),'공통 CAPEX는 AI·메모리·랙·DC에서 같은 원본을 사용합니다. 네 번 노출돼도 독립 신호 한 개입니다.')+panel('다른 모듈이 읽는 데이터 계약','<div class="inline"><a href="data/exports.json" download>앙상블 연동 JSON ↓</a><a href="data/research.json" download>모델·근거 JSON ↓</a><a href="data/operations.json" download>운영 관측 JSON ↓</a></div>','업체 ID, 지표·기간·단위·공표일·근거 그룹·검증 상태를 포함합니다. 월별 추정 출력은 가정과 함께 CSV로 내려받을 수 있습니다.');
}
function setLocation(){const u=new URL(location.href);u.searchParams.set('company',id);u.searchParams.set('view',view);historyReplace(u);if(parent!==window)parent.postMessage({type:'ensemble-cloud-state',company:id,view},location.origin);}
function historyReplace(u){window.history.replaceState(null,'',u);}
function render(){
 const p=ledger.providers[id],providers=Object.values(ledger.providers),s=settings();
 let body;try{body=({overview,capacity:ramp,earnings,calculator,history,evidence,compare,links:integration}[view])();}catch(e){body=panel('입력 확인',empty(e.message)+'<button data-action="reset">기본 가정 복원</button>');}
 root.innerHTML='<div class="layout"><aside class="sidebar"><input class="search" id="company-search" placeholder="업체·티커 검색" aria-label="업체 검색"><div class="companies">'+Object.entries(groupNames).map(([group,name])=>'<div class="group">'+name+'</div>'+providers.filter(p=>p.group===group).sort((a,b)=>(a.id==='NBIS'?-1:b.id==='NBIS'?1:a.name.localeCompare(b.name))).map(p=>'<button class="company '+(p.id===id?'on':'')+'" data-company="'+esc(p.id)+'" data-search="'+esc((p.name+' '+p.id+' '+p.aliases.join(' ')).toLowerCase())+'"><span>'+esc(p.name.replace(/ Group N.V.| Corporation| Limited| Inc\./g,''))+'</span><small>'+esc(p.id)+'</small></button>').join('')).join('')+'</div><p class="note">22개 업체 · 6개 용량 모델<br>공식 실적 대조 '+research.updated+'</p></aside><section class="detail"><select id="mobile-company" class="mobile-select" aria-label="업체 선택">'+providers.map(p=>'<option value="'+esc(p.id)+'"'+(p.id===id?' selected':'')+'>'+esc(p.name+' · '+p.id)+'</option>').join('')+'</select><div class="toolbar"><h2>'+esc(p.name)+'</h2>'+badge(p.id)+badge(groupNames[p.group])+'<span class="meta">'+rowsFor(id).filter(s=>s.verified).length+'개 공식 대조 · '+p.currency+'</span><button data-action="share" class="push-right">현재 화면 링크</button><span id="notice" class="meta"></span></div><nav class="tabs" aria-label="클라우드 화면">'+Object.entries(views).map(([key,label])=>'<button data-view="'+key+'" class="'+(key===view?'on':'')+'" aria-current="'+(key===view?'page':'false')+'">'+label+'</button>').join('')+'</nav>'+body+'<footer class="note">공식 실적 대조 '+research.updated+' · 과거 팔랑크스 스냅샷 '+(archive.cloud?._meta?.generated||'—')+' · '+esc(p.fiscal_note||'결산기·사업 범위를 각 근거에서 확인하세요.')+'</footer></section></div>';
 setLocation();resize();
}
function resize(){if(parent!==window)parent.postMessage({type:'ensemble-cloud-height',height:Math.ceil(document.querySelector('.workspace').scrollHeight)},location.origin);}
function exportCSV(filename,rows,cols){const blob=new Blob([E.csv(rows,cols)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
root.addEventListener('click',async event=>{
 const b=event.target.closest('button');if(!b)return;
 if(b.dataset.company){id=b.dataset.company;selectedMetric='';render();return;}
 if(b.dataset.view){view=b.dataset.view;render();return;}
 const action=b.dataset.action;
 if(action==='reset'){delete stores[id];try{localStorage.removeItem('ensemble-cloud-v2-'+id);}catch{}render();}
 if(action==='ramp-csv'){const f=forecast();const rows=f.rows.flatMap(r=>r.parts.filter(t=>t.mw>0).map(t=>({provider:id,month:r.month,customer:t.customer,capacity_mw:t.mw,unit:r.unit,mw_basis:t.mw_basis,timing_basis:t.timing_basis,annual_rate_m_per_mw:t.rate,monthly_revenue_m:(t.mw+t.previous_mw)/2*t.rate/12*settings().calculator.utilization/100*(1+settings().price/100),model:'scenario',source_url:research.sources[t.source]?.url||'',assumptions:JSON.stringify(settings())})));exportCSV(id+'-monthly-capacity.csv',rows,['provider','month','customer','capacity_mw','unit','mw_basis','timing_basis','annual_rate_m_per_mw','monthly_revenue_m','model','source_url','assumptions']);}
 if(action==='evidence-csv')exportCSV(id+'-evidence.csv',filteredEvidence(),['provider','title','value','unit','period','scope','evidence','verified','source_url','published_at','first_seen_at','verified_at','revision','note']);
 if(action==='share'){const u=new URL('../',location.href);u.hash='tab=cloud&company='+encodeURIComponent(id)+'&view='+view;try{await navigator.clipboard.writeText(u.href);document.getElementById('notice').textContent='링크 복사됨';}catch{document.getElementById('notice').innerHTML=link(u.href,'현재 화면 열기');}}
});
root.addEventListener('input',event=>{
 const e=event.target;
 if(e.id==='company-search')root.querySelectorAll('.company').forEach(b=>{b.hidden=!b.dataset.search.includes(e.value.toLowerCase());});
 if(e.id==='evidence-search'){evidenceSearch=e.value;document.getElementById('evidence-rows').innerHTML=evidenceTable(filteredEvidence());document.getElementById('evidence-count').textContent=filteredEvidence().length+'개';resize();}
 if(e.matches('[data-calc],[data-mix],[data-rate]'))updateCalculator();
});
function updateCalculator(){
 const s=settings(),draft=structuredClone(s.calculator);root.querySelectorAll('[data-calc]').forEach(e=>draft[e.dataset.calc]=e.value===''?NaN:Number(e.value));root.querySelectorAll('[data-mix]').forEach(e=>draft.mix[Number(e.dataset.mix)]=e.value===''?NaN:Number(e.value));root.querySelectorAll('[data-rate]').forEach(e=>draft.rates[Number(e.dataset.rate)]=e.value===''?NaN:Number(e.value));
 try{M.calculate(draft);s.calculator=draft;document.getElementById('calc-output').innerHTML=calcOutput();document.getElementById('calc-error').textContent='';persist();}catch(e){document.getElementById('calc-error').textContent=e.message;document.getElementById('calc-output').innerHTML=empty('입력 오류가 해결되면 계산 결과를 표시합니다.');}resize();
}
root.addEventListener('change',event=>{
 const e=event.target;
 if(e.id==='mobile-company'){id=e.value;selectedMetric='';render();}
 if(e.id==='metric'){selectedMetric=e.value;render();}
 if(e.id==='evidence-filter'){evidenceFilter=e.value;render();}
 if(e.id==='delay'){settings().delay=Number(e.value);persist();render();}
 if(e.dataset.tranche!=null){const s=settings(),draft=structuredClone(s),t=draft.tranches[Number(e.dataset.tranche)],field=e.dataset.field;t[field]=field==='mw'?(e.value===''?NaN:Number(e.value)):e.value;if(field==='mw')t.mw_basis='assumption';t.timing_basis='assumption';t.note='사용자 수정 가정. 원래 근거는 링크에서 확인하세요.';try{M.forecast(research.profiles[id],draft);stores[id]=draft;persist();render();}catch(err){document.getElementById('form-error').textContent=err.message;}}
});
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===parent&&event.data?.type==='ensemble-cloud-resize')resize();});
if(params.get('embed')==='1')document.body.classList.add('embedded');
document.getElementById('asof').textContent='자료 대조 '+research.updated;
if('ResizeObserver' in window)new ResizeObserver(resize).observe(root);
render();
})().catch(error=>{document.getElementById('app').innerHTML='<p>데이터를 불러오지 못했습니다. 새로고침 후 다시 확인해 주세요.</p>';console.error(error);});
