/* W01_VIZ SVG adapter. Pure chart strings; provenance must be supplied by adapters. */
(function(root){'use strict';
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function finite(x){return typeof x==='number'&&isFinite(x);}
function value(x){if(finite(x))return x;if(x&&typeof x==='object'){if(finite(x.value))return x.value;if(finite(x.v))return x.v;if(finite(x.base))return x.base;}return null;}
function role(x,fallback){if(x&&typeof x==='object'){if(/derived|calculated|산출|파생|역산|월합산/.test(String(x.role||x.status||'')))return 'derived';if(x.est===true)return 'forecast';if(x.actual===true)return 'actual';if(x.derived===true)return 'derived';x=x.role||x.status||fallback;}if(typeof x!=='string')x=fallback;x=String(x||fallback||'unknown').toLowerCase();if(/^(actual|reported|실적|공시)$/.test(x))return 'actual';if(/derived|calculated|산출|파생|역산|월합산/.test(x))return 'derived';if(/est|forecast|guidance|forward_plan|announced|추정|전망/.test(x))return 'forecast';return 'unknown';}
function point(x,fallback){return {value:value(x),role:role(x,fallback),lo:x&&typeof x==='object'?value(x.lo):null,hi:x&&typeof x==='object'?value(x.hi):null};}
function theme(){if(typeof document==='undefined')return 'light';var t=document.documentElement.getAttribute('data-theme');if(t==='dark'||t==='light')return t;if(document.documentElement.classList.contains('dark'))return 'dark';return typeof matchMedia!=='undefined'&&matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}
function style(s,r,index){var st=root.VizSeries.applySeriesStyle({index:index,metric_index:index,theme:theme(),metric:s.metric||s.name||s.label||String(index),label:s.name||s.label,unit:s.unit},r),c='var(--w01-p'+(index%root.VIZ_CONTRACT.tokens.palette.light.length)+')';st.stroke=c;st.fill=st.hollow?'var(--w01-bg)':c;return st;}
function themeCSS(){var t=root.VIZ_CONTRACT.tokens;function vars(k){return '--w01-text:'+t.text[k]+';--w01-bg:'+t.background[k]+';'+t.palette[k].map(function(c,i){return '--w01-p'+i+':'+c+';';}).join('');}return '<style>.viz-contract-chart,.viz-legend{'+vars('light')+'}@media(prefers-color-scheme:dark){.viz-contract-chart,.viz-legend{'+vars('dark')+'}}html[data-theme=light] .viz-contract-chart,html[data-theme=light] .viz-legend{'+vars('light')+'}html[data-theme=dark] .viz-contract-chart,html[data-theme=dark] .viz-legend{'+vars('dark')+'}</style>';}

function chart(labels,series,opts){
 opts=opts||{};if(!root.VizScale||!root.VizSeries)throw new Error('W01_VIZ assets missing');
 var W=opts.width||760,H=opts.height||250,L=65,R=65,T=28,B=55,w=W-L-R,h=H-T-B,n=labels.length,ss=[],units=[],metrics=[],i,j;
 for(i=0;i<series.length;i++){var s=series[i],u=s.unit||opts.unit||'원문 단위',p=[];if(units.indexOf(u)<0)units.push(u);for(j=0;j<n;j++){var q=point((s.data||[])[j],s.roles?s.roles[j]:s.role);if(s.lo&&finite(s.lo[j]))q.lo=s.lo[j];if(s.hi&&finite(s.hi[j]))q.hi=s.hi[j];if(q.role==='unknown')q.value=null;p.push(q);}var metric=s.metric||s.name||s.label||String(i);if(metrics.indexOf(metric)<0)metrics.push(metric);ss.push({src:s,unit:u,points:p,axis:units.indexOf(u),index:metrics.indexOf(metric)});}
 if(units.length>2)throw new Error('W01_VIZ: more than 2 unlike units require separate panels');
 var ranges=units.map(function(u,ai){var vals=[],isBar=false;ss.forEach(function(s){if(s.axis!==ai)return;isBar=isBar||s.src.type==='bar';s.points.forEach(function(p){if(p.value!==null){vals.push(p.value);if(finite(p.lo))vals.push(p.lo);if(finite(p.hi))vals.push(p.hi);}});});
 if(opts.stacked){for(var k=0;k<n;k++){var pos=0,neg=0;ss.forEach(function(s){var v=s.points[k].value;if(s.axis===ai&&v!==null){pos+=Math.max(0,v);neg+=Math.min(0,v);}});vals.push(pos,neg);}}
 var cls=opts.stacked||isBar?'zero_anchored':(opts.scale_class||(u==='%'?'ratio':'range_focus'));
 if(opts.percent&&!isBar)cls='ratio';var o={class:cls,scale_class:cls,ratioMax:opts.percent?1:100,allowNegative:true};
 if(finite(opts.reference))o.reference=opts.reference;if(finite(opts.threshold))o.reference=opts.threshold;
 if(cls==='ratio'&&!finite(o.reference))o.reference=opts.percent?1:0;
 if(finite(o.reference))vals.push(o.reference);
 return root.VizScale.niceScale(vals,o);});
 if(root.VizScale.alignZero){var aligned=root.VizScale.alignZero(ranges);ranges=ranges.map(function(r,i){return aligned[i];});}
 function x(k){return L+w*(k+.5)/Math.max(1,n);}function y(v,ai){var r=ranges[ai];return T+h-(v-r.min)/(r.max-r.min)*h;}
 var out=themeCSS()+'<svg class="chart viz-contract-chart" data-viz-contract="W01_VIZ" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+esc(opts.title||'차트')+'" style="width:100%;height:auto;color:var(--w01-text)"><title>'+esc(opts.title||'차트')+'</title>',valid=ss.some(function(s){return s.points.some(function(p){return p.value!==null;});});
 ranges.forEach(function(r,ai){out+='<g data-viz-axis="'+ai+'" data-min="'+r.min+'" data-max="'+r.max+'" data-step="'+r.step+'" data-ticks="'+esc(JSON.stringify(r.ticks))+'" data-scale-class="'+r.scale_class+'">';
 (r.ticks||[]).forEach(function(v){var Y=y(v,ai);if(ai===0)out+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+Y+'" y2="'+Y+'" stroke="currentColor" opacity=".16"/>';var num=opts.percent?(v*100).toFixed(Math.max(0,(r.decimals||0)-2))+'%':(v/(r.divisor||1)).toFixed(r.decimals||0)+(r.suffix||'');out+='<text x="'+(ai?W-R+7:L-7)+'" y="'+(Y+3)+'" text-anchor="'+(ai?'start':'end')+'" font-size="10" fill="currentColor">'+esc(num)+'</text>';});
 out+='<text x="'+(ai?W-R:L)+'" y="14" text-anchor="'+(ai?'end':'start')+'" font-size="10" fill="currentColor">'+esc(units[ai])+'</text>';
 if(r.axis_note)out+='<text data-axis-note="nonzero" x="'+(ai?W-R:L)+'" y="'+(H-5)+'" text-anchor="'+(ai?'end':'start')+'" font-size="10" fill="currentColor">≈ '+esc(r.axis_note)+'</text>';
 if(finite(opts.threshold)&&opts.threshold>=r.min&&opts.threshold<=r.max)out+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y(opts.threshold,ai)+'" y2="'+y(opts.threshold,ai)+'" stroke="currentColor" stroke-dasharray="2 3"/><text x="'+(L+3)+'" y="'+(y(opts.threshold,ai)-4)+'" font-size="10" fill="currentColor">기준 '+esc(opts.percent?opts.threshold*100+'%':opts.threshold)+'</text>';
 out+='</g>';});
 if(!valid)out+='<text x="'+L+'" y="'+(T+30)+'" fill="currentColor">NOT FOUND · 상태 또는 수치 미확인</text>';
 var bars=ss.filter(function(s){return s.src.type==='bar';}),accP=[],accN=[],divider=[];
 ss.forEach(function(s,si){var r=ranges[s.axis],src=s.src,last=null,path='',lastRole=null,barIndex=bars.indexOf(s),group=opts.stacked?1:Math.max(1,bars.length),bw=w/Math.max(1,n)*.66/group;
 function flush(){if(path){var st=style(src,lastRole,s.index);out+='<path data-viz-role="'+lastRole+'" d="'+path+'" fill="none" stroke="'+st.stroke+'" stroke-width="'+st.width+'" stroke-dasharray="'+(st.dash||[]).join(' ')+'"/>';path='';}}
 var band=[];function flushBand(){if(band.length>1){var st=style(src,'forecast',s.index);out+='<path data-viz-band="scenario" d="M '+band.map(function(k){return x(k)+','+y(s.points[k].hi,s.axis);}).join(' L ')+' L '+band.slice().reverse().map(function(k){return x(k)+','+y(s.points[k].lo,s.axis);}).join(' L ')+' Z" fill="'+st.stroke+'" fill-opacity=".14" stroke="'+st.stroke+'" stroke-width="1" stroke-dasharray="3 3"/>';}band=[];}
 s.points.forEach(function(p,k){if(p.value!==null&&p.role==='forecast'&&finite(p.lo)&&finite(p.hi)&&p.lo<=p.value&&p.value<=p.hi)band.push(k);else flushBand();});flushBand();
 s.points.forEach(function(p,k){var v=p.value;if(v===null){flush();last=null;return;}var st=style(src,p.role,s.index),X=x(k),Y=y(v,s.axis),title=labels[k]+' · '+(src.name||src.label||'계열')+' '+v+' '+s.unit+' · '+(p.role==='forecast'&&opts.forecast_start&&String(labels[k])<opts.forecast_start?'과거 추정(est)':st.statusLabel);
 if(p.role==='forecast'&&(!opts.forecast_start||String(labels[k])>=opts.forecast_start)&&divider.indexOf(k)<0&&!s.points.slice(0,k).some(function(a,j){return a.value!==null&&a.role==='forecast'&&(!opts.forecast_start||String(labels[j])>=opts.forecast_start);})){divider.push(k);out+='<line data-viz-divider="forecast" x1="'+X+'" x2="'+X+'" y1="'+T+'" y2="'+(T+h)+'" stroke="'+st.stroke+'" stroke-dasharray="3 3"/><text x="'+(X+3)+'" y="'+(T+10)+'" fill="currentColor" font-size="10">전망 시작</text>';}
 if(p.role==='forecast'&&finite(p.lo)&&finite(p.hi)&&p.lo<=v&&v<=p.hi&&p.lo<p.hi&&(src.type==='bar'||!s.points.some(function(a,j){return Math.abs(j-k)===1&&a.value!==null&&a.role==='forecast'&&finite(a.lo)&&finite(a.hi);} ))){out+='<path data-viz-range="scenario" d="M '+X+' '+y(p.lo,s.axis)+' L '+X+' '+y(p.hi,s.axis)+' M '+(X-4)+' '+y(p.lo,s.axis)+' L '+(X+4)+' '+y(p.lo,s.axis)+' M '+(X-4)+' '+y(p.hi,s.axis)+' L '+(X+4)+' '+y(p.hi,s.axis)+'" fill="none" stroke="'+st.stroke+'" stroke-width="1.2"><title>입력 lo~hi 시나리오 범위</title></path>';}if(src.type==='bar'){var base=0;if(opts.stacked){var a=v>=0?accP:accN;base=a[k]||0;a[k]=base+v;}var yy=y(base+v,s.axis),yy0=y(base,s.axis),bx=opts.stacked?X-bw/2:X-w/n*.33+barIndex*bw;out+='<rect data-viz-role="'+p.role+'" x="'+bx+'" y="'+Math.min(yy,yy0)+'" width="'+bw+'" height="'+Math.abs(yy-yy0)+'" fill="'+(p.role==='forecast'?'none':st.stroke)+'" stroke="'+st.stroke+'" stroke-width="'+st.width+'" stroke-dasharray="'+(st.dash||[]).join(' ')+'"><title>'+esc(title)+'</title></rect>';
 }else{if(lastRole!==p.role){flush();path=last?'M '+last.x+','+last.y+' L '+X+','+Y:'M '+X+','+Y;}else path+=(path?' L ':'M ')+X+','+Y;lastRole=p.role;last={x:X,y:Y};out+=marker(X,Y,st,p.role,title);}
 });flush();});
 var step=Math.max(1,Math.ceil(n/9));labels.forEach(function(lb,k){if(k%step&&k!==n-1)return;out+='<text x="'+x(k)+'" y="'+(H-27)+'" text-anchor="middle" fill="currentColor" font-size="9">'+esc(lb)+'</text>';});out+='</svg>';
 var mode=ss.length<=3?'inline':ss.length<=8?'wrap':'scroll';out+='<div class="viz-legend" data-layout="'+mode+'" style="display:flex;gap:6px 14px;'+(mode==='scroll'?'overflow:auto;max-height:110px;':'flex-wrap:wrap;')+'font-size:11px">';
 ss.forEach(function(s,si){var rs=[];s.points.forEach(function(p){if(p.value!==null&&rs.indexOf(p.role)<0)rs.push(p.role);});if(!rs.length)rs=['unknown'];rs.forEach(function(rr){var st=style(s.src,rr,s.index);out+='<span style="display:inline-flex;align-items:center;gap:5px;white-space:nowrap"><svg width="23" height="12" style="width:23px;height:12px;display:inline-block;flex:none;overflow:visible" aria-hidden="true"><path d="M1 6L22 6" stroke="'+st.stroke+'" stroke-width="'+st.width+'" stroke-dasharray="'+(st.dash||[]).join(' ')+'"/>'+marker(11,6,st,rr,'범례')+'</svg> '+esc((s.src.name||s.src.label||'계열')+' · '+s.unit+' · '+(rr==='forecast'&&opts.forecast_start?'과거 추정 / 전망(est)':st.statusLabel))+'</span>';});});out+='</div>';
 if(ss.some(function(s){return s.points.some(function(p){return p.role==='forecast'&&finite(p.lo)&&finite(p.hi)&&p.hi>p.lo;});}))out+='<div class="note">음영: 입력 lo~hi 시나리오 범위 · 통계 신뢰구간 아님</div>';
 if(units.length>1)out+='<div class="note">단위별 독립 축 · '+(ranges.every(function(r){return r.scale_class==='zero_anchored';})?'두 금액 막대축 0 위치 정렬':'0 위치 일치 보장 없음')+' · 격자는 왼쪽 축만 표시</div>';
 if(ss.some(function(s){return s.points.some(function(p){return p.value===null;});}))out+='<div class="note">NOT FOUND 구간은 연결·0 대체하지 않음'+(opts.stacked?' · 일부 구성 미확인은 부분합':'')+'</div>';
 if(ranges.some(function(r){return !!r.clip_hint;}))out+='<div class="note">이상치 범위 축소 제안 있음 · 이 화면은 전체 값을 유지</div>';
 return out.replace(/<text /g,'<text style="fill:var(--w01-text)" ');
}
function marker(X,Y,st,r,title){var sz=r==='forecast'?3.4:2.6,common=' data-viz-role="'+r+'" data-marker="'+st.marker+'" fill="'+st.fill+'" stroke="'+st.stroke+'" stroke-width="'+(r==='derived'?2.5:1.5)+'"',tail='<title>'+esc(title)+'</title>';if(st.marker==='triangle')return '<path'+common+' d="M '+X+' '+(Y-sz)+' L '+(X+sz)+' '+(Y+sz)+' L '+(X-sz)+' '+(Y+sz)+' Z">'+tail+'</path>';if(st.marker==='rectRot')return '<path'+common+' d="M '+X+' '+(Y-sz)+' L '+(X+sz)+' '+Y+' L '+X+' '+(Y+sz)+' L '+(X-sz)+' '+Y+' Z">'+tail+'</path>';if(st.marker==='rect')return '<rect'+common+' x="'+(X-sz)+'" y="'+(Y-sz)+'" width="'+(sz*2)+'" height="'+(sz*2)+'">'+tail+'</rect>';return '<circle'+common+' cx="'+X+'" cy="'+Y+'" r="'+sz+'">'+tail+'</circle>';}
function mount(svg,html){var box=document.createElement('div');box.innerHTML=html;var rendered=box.querySelector('svg');svg.setAttribute('viewBox',rendered.getAttribute('viewBox'));svg.innerHTML=rendered.innerHTML;svg.setAttribute('data-viz-contract','W01_VIZ');svg.classList.add('viz-contract-chart');svg.setAttribute('style','color:var(--w01-text)');rendered.remove();var old=svg.parentNode.querySelector('[data-viz-caption]');if(old)old.remove();box.setAttribute('data-viz-caption','true');svg.parentNode.appendChild(box);}
root.EnsembleViz={chart:chart,mount:mount,role:role,point:point,value:value};
})(typeof window!=='undefined'?window:globalThis);
